version: "3.8"

x-base: &base
  # Uses the current user's unix id. Run `echo $(id -u):$(id -g)`
  user: ${CURRENT_UID:-1000:1000}

services:
  playwright:
    networks:
      - core
      - userback

networks:
  userback:
    external: true
    name: userback-ingress
