version: "3.8"

# Example Base
#
# Every example's common configuration they all inherit from
x-base: &base
  image: node:16
  networks:
    core:
  volumes:
    - .:/app
  working_dir: /app
  environment:
    - VITE_UB_TOKEN
    - VITE_UB_DOMAIN

services:
  # Example Services
  #
  # Each example will be listed here and run over port 3000 on the `core` networks
  # to allow playwright docker to access all examples.
  example-widget:
    <<: *base
    command: yarn workspace example-js run serve
  example-react:
    <<: *base
    command: yarn workspace example-react run serve
  example-vue:
    <<: *base
    command: yarn workspace example-vue run serve
  example-vue2:
    <<: *base
    command: yarn workspace example-vue2 run serve
  example-nuxt2:
    <<: *base
    command: yarn workspace example-nuxt2 run serve

  # Playwright task
  #
  # Uses profiles to only enable e2e testing when using `docker compose run`
  playwright:
    build:
      context: .
      target: e2e
    networks:
      - core
    profiles: ["e2e"]

networks:
  core:
